apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  selector:
    name: test
  ports:
    - port: 8765
      targetPort: 9376
  externalTrafficPolicy: Cluster
  type: LoadBalancer